# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consultation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consultation.proto',
  package='consultation',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x63onsultation.proto\x12\x0c\x63onsultation\"*\n\rRetortRequest\x12\x19\n\x11original_question\x18\x01 \x01(\t\"\x1d\n\x0bRetortReply\x12\x0e\n\x06retort\x18\x01 \x01(\t2U\n\x0f\x43\x61mpaignManager\x12\x42\n\x06Retort\x12\x1b.consultation.RetortRequest\x1a\x19.consultation.RetortReply\"\x00\x42\x1d\n\x1bnet.yairsovran.consultationb\x06proto3')
)




_RETORTREQUEST = _descriptor.Descriptor(
  name='RetortRequest',
  full_name='consultation.RetortRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='original_question', full_name='consultation.RetortRequest.original_question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=78,
)


_RETORTREPLY = _descriptor.Descriptor(
  name='RetortReply',
  full_name='consultation.RetortReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retort', full_name='consultation.RetortReply.retort', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['RetortRequest'] = _RETORTREQUEST
DESCRIPTOR.message_types_by_name['RetortReply'] = _RETORTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RetortRequest = _reflection.GeneratedProtocolMessageType('RetortRequest', (_message.Message,), dict(
  DESCRIPTOR = _RETORTREQUEST,
  __module__ = 'consultation_pb2'
  # @@protoc_insertion_point(class_scope:consultation.RetortRequest)
  ))
_sym_db.RegisterMessage(RetortRequest)

RetortReply = _reflection.GeneratedProtocolMessageType('RetortReply', (_message.Message,), dict(
  DESCRIPTOR = _RETORTREPLY,
  __module__ = 'consultation_pb2'
  # @@protoc_insertion_point(class_scope:consultation.RetortReply)
  ))
_sym_db.RegisterMessage(RetortReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033net.yairsovran.consultation'))

_CAMPAIGNMANAGER = _descriptor.ServiceDescriptor(
  name='CampaignManager',
  full_name='consultation.CampaignManager',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=111,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='Retort',
    full_name='consultation.CampaignManager.Retort',
    index=0,
    containing_service=None,
    input_type=_RETORTREQUEST,
    output_type=_RETORTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMPAIGNMANAGER)

DESCRIPTOR.services_by_name['CampaignManager'] = _CAMPAIGNMANAGER

# @@protoc_insertion_point(module_scope)
