# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import consultation_pb2 as consultation__pb2


class CampaignManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Retort = channel.unary_unary(
        '/consultation.CampaignManager/Retort',
        request_serializer=consultation__pb2.RetortRequest.SerializeToString,
        response_deserializer=consultation__pb2.RetortReply.FromString,
        )


class CampaignManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Retort(self, request, context):
    """Gives a randomly chosen evasive answer.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CampaignManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Retort': grpc.unary_unary_rpc_method_handler(
          servicer.Retort,
          request_deserializer=consultation__pb2.RetortRequest.FromString,
          response_serializer=consultation__pb2.RetortReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'consultation.CampaignManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
