# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='debate.proto',
  package='debate',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x64\x65\x62\x61te.proto\x12\x06\x64\x65\x62\x61te\"!\n\rAnswerRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1d\n\x0b\x41nswerReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"3\n\x10\x45laborateRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08\x62lah_run\x18\x02 \x03(\x05\" \n\x0e\x45laborateReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2\x84\x01\n\tCandidate\x12\x36\n\x06\x41nswer\x12\x15.debate.AnswerRequest\x1a\x13.debate.AnswerReply\"\x00\x12?\n\tElaborate\x12\x18.debate.ElaborateRequest\x1a\x16.debate.ElaborateReply\"\x00\x42\x18\n\x16net.jeremymuhia.debateb\x06proto3')
)




_ANSWERREQUEST = _descriptor.Descriptor(
  name='AnswerRequest',
  full_name='debate.AnswerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='debate.AnswerRequest.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=57,
)


_ANSWERREPLY = _descriptor.Descriptor(
  name='AnswerReply',
  full_name='debate.AnswerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='debate.AnswerReply.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=88,
)


_ELABORATEREQUEST = _descriptor.Descriptor(
  name='ElaborateRequest',
  full_name='debate.ElaborateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='debate.ElaborateRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blah_run', full_name='debate.ElaborateRequest.blah_run', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=141,
)


_ELABORATEREPLY = _descriptor.Descriptor(
  name='ElaborateReply',
  full_name='debate.ElaborateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='debate.ElaborateReply.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['AnswerRequest'] = _ANSWERREQUEST
DESCRIPTOR.message_types_by_name['AnswerReply'] = _ANSWERREPLY
DESCRIPTOR.message_types_by_name['ElaborateRequest'] = _ELABORATEREQUEST
DESCRIPTOR.message_types_by_name['ElaborateReply'] = _ELABORATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnswerRequest = _reflection.GeneratedProtocolMessageType('AnswerRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANSWERREQUEST,
  __module__ = 'debate_pb2'
  # @@protoc_insertion_point(class_scope:debate.AnswerRequest)
  ))
_sym_db.RegisterMessage(AnswerRequest)

AnswerReply = _reflection.GeneratedProtocolMessageType('AnswerReply', (_message.Message,), dict(
  DESCRIPTOR = _ANSWERREPLY,
  __module__ = 'debate_pb2'
  # @@protoc_insertion_point(class_scope:debate.AnswerReply)
  ))
_sym_db.RegisterMessage(AnswerReply)

ElaborateRequest = _reflection.GeneratedProtocolMessageType('ElaborateRequest', (_message.Message,), dict(
  DESCRIPTOR = _ELABORATEREQUEST,
  __module__ = 'debate_pb2'
  # @@protoc_insertion_point(class_scope:debate.ElaborateRequest)
  ))
_sym_db.RegisterMessage(ElaborateRequest)

ElaborateReply = _reflection.GeneratedProtocolMessageType('ElaborateReply', (_message.Message,), dict(
  DESCRIPTOR = _ELABORATEREPLY,
  __module__ = 'debate_pb2'
  # @@protoc_insertion_point(class_scope:debate.ElaborateReply)
  ))
_sym_db.RegisterMessage(ElaborateReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026net.jeremymuhia.debate'))

_CANDIDATE = _descriptor.ServiceDescriptor(
  name='Candidate',
  full_name='debate.Candidate',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=178,
  serialized_end=310,
  methods=[
  _descriptor.MethodDescriptor(
    name='Answer',
    full_name='debate.Candidate.Answer',
    index=0,
    containing_service=None,
    input_type=_ANSWERREQUEST,
    output_type=_ANSWERREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Elaborate',
    full_name='debate.Candidate.Elaborate',
    index=1,
    containing_service=None,
    input_type=_ELABORATEREQUEST,
    output_type=_ELABORATEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CANDIDATE)

DESCRIPTOR.services_by_name['Candidate'] = _CANDIDATE

# @@protoc_insertion_point(module_scope)
